namespace Shared.EmailBuilder.Classes
{
    public enum EmailType
    {
        None,
        ActivateAccountOneTimePassword,
        ForgotPasswordOneTimePassword,
        NameUpdated,
        UpdateEmailOneTimePassword,
        EmailUpdated,
        PasswordUpdated,
        ProfileImageUpdated,
        CollaboratorJoinedList,
        UserJoinedList,
        UserRemovedFromList,
        CollaboratorRemovedFromList,
        UserRemovedCollaborator,
        CollaboratorAddedListItem,
        UserAddedListItem,
        CollaboratorRemovedListItem,
        UserRemovedListItem,
        CollaboratorMovedListItem,
        UserMovedListItem,
        CollaboratorUpdatedList,
        UserUpdatedList,
        CollaboratorDeletedList,
        UserDeletedList,
        ItemReviewed,
        DeleteAccountOneTimePassword,
        AccountDeleted,
        WelcomeToNicheShack,
        NoncompliantStrikeList,
        NoncompliantStrikeUserImage,
        NoncompliantStrikeUserName,
        NoncompliantStrikeReview,
        UserAccountTerminated,
        MessageReply
    }
}